### ISSUE TITLE
Add function FfbRegisterGenCB to get FFB effects

### ISSUE THREAD

**Issue by danieltian** [jangxx/node-vjoy#2]
Would it be possible to add the function `FfbRegisterGenCB` so that FFB effects sent to vJoy can be picked up by this library? Currently I'm using a C# feeder to expose the FFB data through UDP, which is then read by an Electron app:

https://github.com/danieltian/cls-ffb/blob/master/vJoyUdpFeeder/vJoyUdpFeeder/Program.cs#L88

But it would be great if I could do this natively with `node-vjoy` instead of having to run the C# feeder in the background.

**Comment by jangxx** [comment]
If I recall correctly, the reason for skipping that function was, that the callback code would be executed in the thread/process of the application using the input (e.g. a game) instead of the process of the feeder. This project was my first native node addon however, and I've learned quite a bit since then, so I might take another crack at it in the coming days.

**Comment by danieltian** [comment]
I don't believe that's the case. The game sends a FFB command to the joystick, and the joystick handles the FFB effect. This is handled through the PID protocol instead of the HID protocol, and I believe vJoy handles it as a callback because it's not necessarily called every frame.

If you find time to implement it, that would be super!

**Comment by jangxx** [comment]
The vJoy SDK documentation specifically states:

> Once registered, the user-defined FFB callback function is called by a vJoy device every time a new FFB packet arrives from the source application. This function is called in the application thread and is blocking. This means that you must return from the FFB callback function ASAP – never wait in this function for the next FFB packet!

I don't know the specifics of dinput or the way Windows handles these things, but I'm guessing that the vJoy driver is called synchronously whenever the game calls the specific force-feedback functions. The driver then calls the callback and only when the callback returns, the blocking ffb call in the game returns as well. This means, that I have to somehow send a notification from the application thread to the Node thread without blocking for too long, otherwise the game would just freeze for a few milliseconds. Luckily, the `node-addon-api` has a built-in class, which does exactly what we need, so implementing this _should_ be fairly simple. I'll see what I can do.

**Comment by danieltian** [comment]
I just tested this in IL-2 and DCS by adding a 1-second `Thread.Sleep` to the FFB callback and you're right. The game won't freeze, but it will stop accepting any inputs from some (though not all) connected devices. For example, the keyboard and joystick inputs will no longer be read, but the mouse still works. Thanks for pointing it out!

**Comment by jangxx** [comment]
Okay, so I'm almost finished with the implementation. I'll finish the last touches as well as the documentation tomorrow, but you can take a look or play around with the code already, if you want. Take a look at _examples/force_feedback.js_ to get an idea of how the new methods work and let me know if I missed something or if something doesn't work.

**Comment by jangxx** [comment]
I've completed the documentation and submitted the new version to npm. If you have further questions, feel free to ask them here, or in a new issue.
