### ISSUE TITLE
Typescript types

### ISSUE THREAD

**Issue by mikey0000** [jangxx/node-vjoy#6]
pretty please.

**Comment by jangxx** [comment]
I'm kinda busy at the moment, so I don't really have time for this right now. PRs are always welcome though.

In the meantime I can redirect you to this other project of mine, which _does_ have TypeScript types: https://github.com/jangxx/node-ViGEmClient It creates XInput controllers instead of DirectInput ones, but maybe that is still useful to you.

**Comment by mikey0000** [comment]
PR'ed with basic typescript types
https://github.com/jangxx/node-vjoy/pull/7

**Comment by jangxx** [comment]
Thanks! Can you try the latest version from npm and then close this if you don't run into any issues?

**Comment by mikey0000** [comment]
resolved
